version: "3.9"
services:
  db:
    image: postgres:13.7
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - bungo_network
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    networks:
      - bungo_network
networks:
  bungo_network:
