version: "3.9"
services:
  db:
    image: postgres:13.7
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - bungo_network
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/myapp
      - "bundle:/usr/local/bundle"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - bungo_network
networks:
  bungo_network:
volumes:
  bundle:
  db:
